name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev   # 强制检出 dev 分支

          
      - name: Change package name for dev release
        run: sed -i 's/^name = "opentdx"/name = "opentdx-dev"/' pyproject.toml
  
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build
        run: uv build

      - name: Publish to PyPI
        run: uv publish --token ${{ secrets.PYPI_API_TOKEN_DEV }}
